print ("Christalyn O. Alano")
print ("Sihi, Buenavista, Marinduque")
print ("December 9, 2002")
print ("Marinduque State College")
print ("Bachelor of Science in Information and Technology")
print ("2nd Year")
print ("Section B")
print ("*MY FAVORITE HOBBIES*")
print ("Travelling")
print ("Singing")
print ("Watching K-drama and Movies")
print ("Drawing")
print ("Reading History")